# Reference: https://taskfile.dev

version: '3'

vars:
  COVERAGE_DIR: .coverage

tasks:
  test:
    desc: Run tests and save coverage to {{.MIGRATION_DIR}}
    cmds:
      - mkdir -p {{ coverage_dir }}
      - go test -coverprofile={{ coverage_dir }}/coverage.out ./...
      - go tool cover -html={{ coverage_dir }}/coverage.out -o ./{{ coverage_dir }}/coverage.html
