package conformance

var documentationContractRows = []contractRow{
	{ID: "helix:architecture", Kind: "docs-anchor", Package: "helix", Anchor: "Anchor: architecture"},
	{ID: "helix:custom-http-client", Kind: "docs-anchor", Package: "helix", Anchor: "Anchor: custom-http-client"},
	{ID: "helix:token-source", Kind: "docs-anchor", Package: "helix", Anchor: "Anchor: token-source"},
	{ID: "helix:response-and-errors", Kind: "docs-anchor", Package: "helix", Anchor: "Anchor: response-and-errors"},
	{ID: "helix:rate-limit-policy", Kind: "docs-anchor", Package: "helix", Anchor: "Anchor: rate-limit-policy"},
	{ID: "helix:replay-policy", Kind: "docs-anchor", Package: "helix", Anchor: "Anchor: replay-policy"},
	{ID: "helix:pager-semantics", Kind: "docs-anchor", Package: "helix", Anchor: "Anchor: pager-semantics"},
	{ID: "helix:experimental-compatibility", Kind: "docs-anchor", Package: "helix", Anchor: "Anchor: experimental-compatibility"},
	{ID: "helix:special-formats", Kind: "docs-anchor", Package: "helix", Anchor: "Anchor: special-formats"},
	{ID: "oauth:oauth-architecture", Kind: "docs-anchor", Package: "oauth", Anchor: "Anchor: oauth-architecture"},
	{ID: "oauth:oauth-lifecycle", Kind: "docs-anchor", Package: "oauth", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:refresh-rotation-hooks", Kind: "docs-anchor", Package: "oauth", Anchor: "Anchor: refresh-rotation-hooks"},
	{ID: "oauth:managed-session-close", Kind: "docs-anchor", Package: "oauth", Anchor: "Anchor: managed-session-close"},
	{ID: "oauth:token-source-contract", Kind: "docs-anchor", Package: "oauth", Anchor: "Anchor: token-source-contract"},
	{ID: "oauth:oauth-errors", Kind: "docs-anchor", Package: "oauth", Anchor: "Anchor: oauth-errors"},
	{ID: "helix:Client", Kind: "exported-symbol", Package: "helix", Symbol: "Client", Anchor: "Anchor: architecture"},
	{ID: "helix:Option", Kind: "exported-symbol", Package: "helix", Symbol: "Option", Anchor: "Anchor: architecture"},
	{ID: "helix:New", Kind: "exported-symbol", Package: "helix", Symbol: "New", Anchor: "Anchor: architecture"},
	{ID: "helix:WithHTTPClient", Kind: "exported-symbol", Package: "helix", Symbol: "WithHTTPClient", Anchor: "Anchor: custom-http-client"},
	{ID: "helix:WithBaseURL", Kind: "exported-symbol", Package: "helix", Symbol: "WithBaseURL", Anchor: "Anchor: architecture"},
	{ID: "helix:WithUserAgent", Kind: "exported-symbol", Package: "helix", Symbol: "WithUserAgent", Anchor: "Anchor: architecture"},
	{ID: "helix:WithTokenSource", Kind: "exported-symbol", Package: "helix", Symbol: "WithTokenSource", Anchor: "Anchor: token-source"},
	{ID: "helix:WithStaticToken", Kind: "exported-symbol", Package: "helix", Symbol: "WithStaticToken", Anchor: "Anchor: token-source"},
	{ID: "helix:WithRateLimitPolicy", Kind: "exported-symbol", Package: "helix", Symbol: "WithRateLimitPolicy", Anchor: "Anchor: rate-limit-policy"},
	{ID: "helix:Credential", Kind: "exported-symbol", Package: "helix", Symbol: "Credential", Anchor: "Anchor: token-source"},
	{ID: "helix:CredentialSnapshot", Kind: "exported-symbol", Package: "helix", Symbol: "CredentialSnapshot", Anchor: "Anchor: token-source"},
	{ID: "helix:NewCredentialSnapshot", Kind: "exported-symbol", Package: "helix", Symbol: "NewCredentialSnapshot", Anchor: "Anchor: token-source"},
	{ID: "helix:TokenSource", Kind: "exported-symbol", Package: "helix", Symbol: "TokenSource", Anchor: "Anchor: token-source"},
	{ID: "helix:RefreshableTokenSource", Kind: "exported-symbol", Package: "helix", Symbol: "RefreshableTokenSource", Anchor: "Anchor: token-source"},
	{ID: "helix:TokenClass", Kind: "exported-symbol", Package: "helix", Symbol: "TokenClass", Anchor: "Anchor: token-source"},
	{ID: "helix:RefreshReason", Kind: "exported-symbol", Package: "helix", Symbol: "RefreshReason", Anchor: "Anchor: token-source"},
	{ID: "helix:Response", Kind: "exported-symbol", Package: "helix", Symbol: "Response", Anchor: "Anchor: response-and-errors"},
	{ID: "helix:Pagination", Kind: "exported-symbol", Package: "helix", Symbol: "Pagination", Anchor: "Anchor: pager-semantics"},
	{ID: "helix:ResponseMeta", Kind: "exported-symbol", Package: "helix", Symbol: "ResponseMeta", Anchor: "Anchor: response-and-errors"},
	{ID: "helix:RateLimit", Kind: "exported-symbol", Package: "helix", Symbol: "RateLimit", Anchor: "Anchor: rate-limit-policy"},
	{ID: "helix:RateLimitPolicy", Kind: "exported-symbol", Package: "helix", Symbol: "RateLimitPolicy", Anchor: "Anchor: rate-limit-policy"},
	{ID: "helix:Pager", Kind: "exported-symbol", Package: "helix", Symbol: "Pager", Anchor: "Anchor: pager-semantics"},
	{ID: "helix:PagerOption", Kind: "exported-symbol", Package: "helix", Symbol: "PagerOption", Anchor: "Anchor: pager-semantics"},
	{ID: "helix:WithPageLimit", Kind: "exported-symbol", Package: "helix", Symbol: "WithPageLimit", Anchor: "Anchor: pager-semantics"},
	{ID: "helix:TransportError", Kind: "exported-symbol", Package: "helix", Symbol: "TransportError", Anchor: "Anchor: response-and-errors"},
	{ID: "helix:ProtocolError", Kind: "exported-symbol", Package: "helix", Symbol: "ProtocolError", Anchor: "Anchor: response-and-errors"},
	{ID: "helix:APIError", Kind: "exported-symbol", Package: "helix", Symbol: "APIError", Anchor: "Anchor: response-and-errors"},
	{ID: "helix:AuthError", Kind: "exported-symbol", Package: "helix", Symbol: "AuthError", Anchor: "Anchor: response-and-errors"},
	{ID: "helix:RateLimitError", Kind: "exported-symbol", Package: "helix", Symbol: "RateLimitError", Anchor: "Anchor: response-and-errors"},
	{ID: "helix:Experimental", Kind: "exported-symbol", Package: "helix", Symbol: "Experimental", Anchor: "Anchor: experimental-compatibility"},
	{ID: "oauth:Client", Kind: "exported-symbol", Package: "oauth", Symbol: "Client", Anchor: "Anchor: oauth-architecture"},
	{ID: "oauth:Option", Kind: "exported-symbol", Package: "oauth", Symbol: "Option", Anchor: "Anchor: oauth-architecture"},
	{ID: "oauth:New", Kind: "exported-symbol", Package: "oauth", Symbol: "New", Anchor: "Anchor: oauth-architecture"},
	{ID: "oauth:WithHTTPClient", Kind: "exported-symbol", Package: "oauth", Symbol: "WithHTTPClient", Anchor: "Anchor: oauth-architecture"},
	{ID: "oauth:WithBaseURL", Kind: "exported-symbol", Package: "oauth", Symbol: "WithBaseURL", Anchor: "Anchor: oauth-architecture"},
	{ID: "oauth:WithRandom", Kind: "exported-symbol", Package: "oauth", Symbol: "WithRandom", Anchor: "Anchor: oauth-architecture"},
	{ID: "oauth:WithClock", Kind: "exported-symbol", Package: "oauth", Symbol: "WithClock", Anchor: "Anchor: oauth-architecture"},
	{ID: "oauth:AuthorizationRequest", Kind: "exported-symbol", Package: "oauth", Symbol: "AuthorizationRequest", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:Authorization", Kind: "exported-symbol", Package: "oauth", Symbol: "Authorization", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:AuthorizationResult", Kind: "exported-symbol", Package: "oauth", Symbol: "AuthorizationResult", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:ClientCredentialsRequest", Kind: "exported-symbol", Package: "oauth", Symbol: "ClientCredentialsRequest", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:ExchangeCodeRequest", Kind: "exported-symbol", Package: "oauth", Symbol: "ExchangeCodeRequest", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:DeviceAuthorizationRequest", Kind: "exported-symbol", Package: "oauth", Symbol: "DeviceAuthorizationRequest", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:DeviceAuthorization", Kind: "exported-symbol", Package: "oauth", Symbol: "DeviceAuthorization", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:PollDeviceTokenRequest", Kind: "exported-symbol", Package: "oauth", Symbol: "PollDeviceTokenRequest", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:RefreshRequest", Kind: "exported-symbol", Package: "oauth", Symbol: "RefreshRequest", Anchor: "Anchor: refresh-rotation-hooks"},
	{ID: "oauth:ValidateRequest", Kind: "exported-symbol", Package: "oauth", Symbol: "ValidateRequest", Anchor: "Anchor: managed-session-close"},
	{ID: "oauth:RevokeRequest", Kind: "exported-symbol", Package: "oauth", Symbol: "RevokeRequest", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:ResponseType", Kind: "exported-symbol", Package: "oauth", Symbol: "ResponseType", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:TokenPair", Kind: "exported-symbol", Package: "oauth", Symbol: "TokenPair", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:Validation", Kind: "exported-symbol", Package: "oauth", Symbol: "Validation", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:CredentialHook", Kind: "exported-symbol", Package: "oauth", Symbol: "CredentialHook", Anchor: "Anchor: refresh-rotation-hooks"},
	{ID: "oauth:SourceOption", Kind: "exported-symbol", Package: "oauth", Symbol: "SourceOption", Anchor: "Anchor: refresh-rotation-hooks"},
	{ID: "oauth:WithRefreshSkew", Kind: "exported-symbol", Package: "oauth", Symbol: "WithRefreshSkew", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:RefreshingTokenSource", Kind: "exported-symbol", Package: "oauth", Symbol: "RefreshingTokenSource", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:NewRefreshingTokenSource", Kind: "exported-symbol", Package: "oauth", Symbol: "NewRefreshingTokenSource", Anchor: "Anchor: refresh-rotation-hooks"},
	{ID: "oauth:TransportError", Kind: "exported-symbol", Package: "oauth", Symbol: "TransportError", Anchor: "Anchor: oauth-errors"},
	{ID: "oauth:ProtocolError", Kind: "exported-symbol", Package: "oauth", Symbol: "ProtocolError", Anchor: "Anchor: oauth-errors"},
	{ID: "oauth:OAuthError", Kind: "exported-symbol", Package: "oauth", Symbol: "OAuthError", Anchor: "Anchor: oauth-errors"},
	{ID: "oauth:DeviceAuthorizationError", Kind: "exported-symbol", Package: "oauth", Symbol: "DeviceAuthorizationError", Anchor: "Anchor: oauth-errors"},
	{ID: "oauth:ManagedSession", Kind: "exported-symbol", Package: "oauth", Symbol: "ManagedSession", Anchor: "Anchor: managed-session-close"},
	{ID: "oauth:NewManagedSession", Kind: "exported-symbol", Package: "oauth", Symbol: "NewManagedSession", Anchor: "Anchor: managed-session-close"},
	{ID: "oauth:SessionOption", Kind: "exported-symbol", Package: "oauth", Symbol: "SessionOption", Anchor: "Anchor: managed-session-close"},
	{ID: "oauth:WithValidationInterval", Kind: "exported-symbol", Package: "oauth", Symbol: "WithValidationInterval", Anchor: "Anchor: managed-session-close"},
	{ID: "oauth:WithValidationErrorHook", Kind: "exported-symbol", Package: "oauth", Symbol: "WithValidationErrorHook", Anchor: "Anchor: managed-session-close"},
	{ID: "oauth:ClientCredentials", Kind: "exported-symbol", Package: "oauth", Symbol: "Client.ClientCredentials", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:ExchangeCode", Kind: "exported-symbol", Package: "oauth", Symbol: "Client.ExchangeCode", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:Refresh", Kind: "exported-symbol", Package: "oauth", Symbol: "Client.Refresh", Anchor: "Anchor: refresh-rotation-hooks"},
	{ID: "oauth:Validate", Kind: "exported-symbol", Package: "oauth", Symbol: "Client.Validate", Anchor: "Anchor: managed-session-close"},
	{ID: "oauth:Revoke", Kind: "exported-symbol", Package: "oauth", Symbol: "Client.Revoke", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:StartDeviceAuthorization", Kind: "exported-symbol", Package: "oauth", Symbol: "Client.StartDeviceAuthorization", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:PollDeviceToken", Kind: "exported-symbol", Package: "oauth", Symbol: "Client.PollDeviceToken", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:AuthorizationURL", Kind: "exported-symbol", Package: "oauth", Symbol: "Client.AuthorizationURL", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "oauth:ParseAuthorizationCallback", Kind: "exported-symbol", Package: "oauth", Symbol: "Client.ParseAuthorizationCallback", Anchor: "Anchor: oauth-lifecycle"},
	{ID: "helix:stable-endpoints", Kind: "descriptor-surface", Package: "helix", Anchor: "Anchor: architecture", Stability: "stable"},
	{ID: "helix:experimental-endpoints", Kind: "descriptor-surface", Package: "helix", Anchor: "Anchor: experimental-compatibility", Stability: "experimental"},
}
