package manifest

import "net/http"

var chatOperations = operationsForGroup("Chat",
	defineOperation("get-chatters", Operation{
		Name:           "Get Chatters",
		Method:         http.MethodGet,
		Path:           "/helix/chat/chatters",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:read:chatters"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "first", Type: "Integer"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Chat",
			ServiceType:    "ChatService",
			Method:         "GetChatters",
			Signature:      "func (s *ChatService) GetChatters(ctx context.Context, req GetChattersRequest) (*Response[GetChattersData], error)",
			PagerSignature: pagerSignature("func (s *ChatService) GetChattersPager(req GetChattersRequest, opts ...PagerOption) (*Pager[GetChattersData], error)"),
			RequestType:    "GetChattersRequest",
			DataType:       "GetChattersData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-chatters",
	}),
	defineOperation("get-channel-emotes", Operation{
		Name:           "Get Channel Emotes",
		Method:         http.MethodGet,
		Path:           "/helix/chat/emotes",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "GetChannelEmotes",
			Signature:   "func (s *ChatService) GetChannelEmotes(ctx context.Context, req GetChannelEmotesRequest) (*Response[GetChannelEmotesData], error)",
			RequestType: "GetChannelEmotesRequest",
			DataType:    "GetChannelEmotesData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-channel-emotes",
	}),
	defineOperation("get-global-emotes", Operation{
		Name:           "Get Global Emotes",
		Method:         http.MethodGet,
		Path:           "/helix/chat/emotes/global",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "GetGlobalEmotes",
			Signature:   "func (s *ChatService) GetGlobalEmotes(ctx context.Context, req GetGlobalEmotesRequest) (*Response[GetGlobalEmotesData], error)",
			RequestType: "GetGlobalEmotesRequest",
			DataType:    "GetGlobalEmotesData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-global-emotes",
	}),
	defineOperation("get-emote-sets", Operation{
		Name:           "Get Emote Sets",
		Method:         http.MethodGet,
		Path:           "/helix/chat/emotes/set",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "emote_set_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "GetEmoteSets",
			Signature:   "func (s *ChatService) GetEmoteSets(ctx context.Context, req GetEmoteSetsRequest) (*Response[GetEmoteSetsData], error)",
			RequestType: "GetEmoteSetsRequest",
			DataType:    "GetEmoteSetsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-emote-sets",
	}),
	defineOperation("get-channel-chat-badges", Operation{
		Name:           "Get Channel Chat Badges",
		Method:         http.MethodGet,
		Path:           "/helix/chat/badges",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameter": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "GetChannelChatBadges",
			Signature:   "func (s *ChatService) GetChannelChatBadges(ctx context.Context, req GetChannelChatBadgesRequest) (*Response[GetChannelChatBadgesData], error)",
			RequestType: "GetChannelChatBadgesRequest",
			DataType:    "GetChannelChatBadgesData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-channel-chat-badges",
	}),
	defineOperation("get-global-chat-badges", Operation{
		Name:           "Get Global Chat Badges",
		Method:         http.MethodGet,
		Path:           "/helix/chat/badges/global",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "GetGlobalChatBadges",
			Signature:   "func (s *ChatService) GetGlobalChatBadges(ctx context.Context, req GetGlobalChatBadgesRequest) (*Response[GetGlobalChatBadgesData], error)",
			RequestType: "GetGlobalChatBadgesRequest",
			DataType:    "GetGlobalChatBadgesData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-global-chat-badges",
	}),
	defineOperation("get-chat-settings", Operation{
		Name:           "Get Chat Settings",
		Method:         http.MethodGet,
		Path:           "/helix/chat/settings",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "GetChatSettings",
			Signature:   "func (s *ChatService) GetChatSettings(ctx context.Context, req GetChatSettingsRequest) (*Response[GetChatSettingsData], error)",
			RequestType: "GetChatSettingsRequest",
			DataType:    "GetChatSettingsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-chat-settings",
	}),
	defineOperation("get-shared-chat-session", Operation{
		Name:           "Get Shared Chat Session",
		Method:         http.MethodGet,
		Path:           "/helix/shared_chat/session",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 500}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "GetSharedChatSession",
			Signature:   "func (s *ChatService) GetSharedChatSession(ctx context.Context, req GetSharedChatSessionRequest) (*Response[GetSharedChatSessionData], error)",
			RequestType: "GetSharedChatSessionRequest",
			DataType:    "GetSharedChatSessionData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-shared-chat-session",
	}),
	defineOperation("get-user-emotes", Operation{
		Name:           "Get User Emotes",
		Method:         http.MethodGet,
		Path:           "/helix/chat/emotes/user",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"user:read:emotes"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String", Required: true},
					{Name: "after", Type: "String"},
					{Name: "broadcaster_id", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Chat",
			ServiceType:    "ChatService",
			Method:         "GetUserEmotes",
			Signature:      "func (s *ChatService) GetUserEmotes(ctx context.Context, req GetUserEmotesRequest) (*Response[GetUserEmotesData], error)",
			PagerSignature: pagerSignature("func (s *ChatService) GetUserEmotesPager(req GetUserEmotesRequest, opts ...PagerOption) (*Pager[GetUserEmotesData], error)"),
			RequestType:    "GetUserEmotesRequest",
			DataType:       "GetUserEmotesData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-user-emotes",
	}),
	defineOperation("update-chat-settings", Operation{
		Name:           "Update Chat Settings",
		Method:         http.MethodPatch,
		Path:           "/helix/chat/settings",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:chat_settings"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "emote_mode", Type: "Boolean"},
					{Name: "follower_mode", Type: "Boolean"},
					{Name: "follower_mode_duration", Type: "Integer"},
					{Name: "non_moderator_chat_delay", Type: "Boolean"},
					{Name: "non_moderator_chat_delay_duration", Type: "Integer"},
					{Name: "slow_mode", Type: "Boolean"},
					{Name: "slow_mode_wait_time", Type: "Integer"},
					{Name: "subscriber_mode", Type: "Boolean"},
					{Name: "unique_chat_mode", Type: "Boolean"},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "UpdateChatSettings",
			Signature:   "func (s *ChatService) UpdateChatSettings(ctx context.Context, req UpdateChatSettingsRequest) (*Response[UpdateChatSettingsData], error)",
			RequestType: "UpdateChatSettingsRequest",
			DataType:    "UpdateChatSettingsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-chat-settings",
	}),
	defineOperation("send-chat-announcement", Operation{
		Name:           "Send Chat Announcement",
		Method:         http.MethodPost,
		Path:           "/helix/chat/announcements",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:announcements", "user:bot", "channel:bot"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "message", Type: "String", Required: true},
					{Name: "color", Type: "String"},
					{Name: "for_source_only", Type: "Boolean"},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "SendChatAnnouncement",
			Signature:   "func (s *ChatService) SendChatAnnouncement(ctx context.Context, req SendChatAnnouncementRequest) (*Response[SendChatAnnouncementData], error)",
			RequestType: "SendChatAnnouncementRequest",
			DataType:    "SendChatAnnouncementData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#send-chat-announcement",
	}),
	defineOperation("send-a-shoutout", Operation{
		Name:           "Send a Shoutout",
		Method:         http.MethodPost,
		Path:           "/helix/chat/shoutouts",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:shoutouts", "user:bot", "channel:bot"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "from_broadcaster_id", Type: "String", Required: true},
					{Name: "to_broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 403, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "SendShoutout",
			Signature:   "func (s *ChatService) SendShoutout(ctx context.Context, req SendShoutoutRequest) (*Response[SendShoutoutData], error)",
			RequestType: "SendShoutoutRequest",
			DataType:    "SendShoutoutData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#send-a-shoutout",
	}),
	defineOperation("send-chat-message", Operation{
		Name:           "Send Chat Message",
		Method:         http.MethodPost,
		Path:           "/helix/chat/messages",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"user:write:chat", "user:bot", "channel:bot"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "sender_id", Type: "String", Required: true},
					{Name: "message", Type: "String", Required: true},
					{Name: "reply_parent_message_id", Type: "String"},
					{Name: "for_source_only", Type: "Bool"},
					{Name: "pin", Type: "Boolean"},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 422, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "SendChatMessage",
			Signature:   "func (s *ChatService) SendChatMessage(ctx context.Context, req SendChatMessageRequest) (*Response[SendChatMessageData], error)",
			RequestType: "SendChatMessageRequest",
			DataType:    "SendChatMessageData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#send-chat-message",
	}),
	defineOperation("get-pinned-chat-message", Operation{
		Name:           "Get Pinned Chat Message",
		Method:         http.MethodGet,
		Path:           "/helix/chat/pins",
		Stability:      StabilityNew,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:chat_messages", "moderator:read:chat_messages", "user:bot", "channel:bot"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 500}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.Chat",
			ServiceType: "ExperimentalChatService",
			Method:      "GetPinnedChatMessage",
			Signature:   "func (s *ExperimentalChatService) GetPinnedChatMessage(ctx context.Context, req GetPinnedChatMessageRequest) (*Response[GetPinnedChatMessageData], error)",
			RequestType: "GetPinnedChatMessageRequest",
			DataType:    "GetPinnedChatMessageData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-pinned-chat-message",
	}),
	defineOperation("pin-chat-message", Operation{
		Name:           "Pin Chat Message",
		Method:         http.MethodPut,
		Path:           "/helix/chat/pins",
		Stability:      StabilityNew,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:chat_messages", "user:bot", "channel:bot"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "message_id", Type: "String", Required: true},
					{Name: "duration_seconds", Type: "Integer"},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 403, 404, 409, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.Chat",
			ServiceType: "ExperimentalChatService",
			Method:      "PinChatMessage",
			Signature:   "func (s *ExperimentalChatService) PinChatMessage(ctx context.Context, req PinChatMessageRequest) (*Response[PinChatMessageData], error)",
			RequestType: "PinChatMessageRequest",
			DataType:    "PinChatMessageData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#pin-chat-message",
	}),
	defineOperation("update-pinned-chat-message", Operation{
		Name:           "Update Pinned Chat Message",
		Method:         http.MethodPatch,
		Path:           "/helix/chat/pins",
		Stability:      StabilityNew,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:chat_messages", "user:bot", "channel:bot"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "message_id", Type: "String", Required: true},
					{Name: "duration_seconds", Type: "Integer"},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 403, 404, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.Chat",
			ServiceType: "ExperimentalChatService",
			Method:      "UpdatePinnedChatMessage",
			Signature:   "func (s *ExperimentalChatService) UpdatePinnedChatMessage(ctx context.Context, req UpdatePinnedChatMessageRequest) (*Response[UpdatePinnedChatMessageData], error)",
			RequestType: "UpdatePinnedChatMessageRequest",
			DataType:    "UpdatePinnedChatMessageData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-pinned-chat-message",
	}),
	defineOperation("unpin-chat-message", Operation{
		Name:           "Unpin Chat Message",
		Method:         http.MethodDelete,
		Path:           "/helix/chat/pins",
		Stability:      StabilityNew,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:chat_messages", "user:bot", "channel:bot"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "message_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 403, 404, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.Chat",
			ServiceType: "ExperimentalChatService",
			Method:      "UnpinChatMessage",
			Signature:   "func (s *ExperimentalChatService) UnpinChatMessage(ctx context.Context, req UnpinChatMessageRequest) (*Response[UnpinChatMessageData], error)",
			RequestType: "UnpinChatMessageRequest",
			DataType:    "UnpinChatMessageData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#unpin-chat-message",
	}),
	defineOperation("get-user-chat-color", Operation{
		Name:           "Get User Chat Color",
		Method:         http.MethodGet,
		Path:           "/helix/chat/color",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "GetUserChatColor",
			Signature:   "func (s *ChatService) GetUserChatColor(ctx context.Context, req GetUserChatColorRequest) (*Response[GetUserChatColorData], error)",
			RequestType: "GetUserChatColorRequest",
			DataType:    "GetUserChatColorData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-user-chat-color",
	}),
	defineOperation("update-user-chat-color", Operation{
		Name:           "Update User Chat Color",
		Method:         http.MethodPut,
		Path:           "/helix/chat/color",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"user:manage:chat_color"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String", Required: true},
					{Name: "color", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Chat",
			ServiceType: "ChatService",
			Method:      "UpdateUserChatColor",
			Signature:   "func (s *ChatService) UpdateUserChatColor(ctx context.Context, req UpdateUserChatColorRequest) (*Response[UpdateUserChatColorData], error)",
			RequestType: "UpdateUserChatColorRequest",
			DataType:    "UpdateUserChatColorData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-user-chat-color",
	}),
)
