package manifest

import "net/http"

var extensionsOperations = operationsForGroup("Extensions",
	defineOperation("get-extension-configuration-segment", Operation{
		Name:           "Get Extension Configuration Segment",
		Method:         http.MethodGet,
		Path:           "/helix/extensions/configurations",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUnknown},
		Scopes:         []string{"unknown"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String"},
					{Name: "extension_id", Type: "String", Required: true},
					{Name: "segment", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Extensions",
			ServiceType: "ExtensionsService",
			Method:      "GetExtensionConfigurationSegment",
			Signature:   "func (s *ExtensionsService) GetExtensionConfigurationSegment(ctx context.Context, req GetExtensionConfigurationSegmentRequest) (*Response[GetExtensionConfigurationSegmentData], error)",
			RequestType: "GetExtensionConfigurationSegmentRequest",
			DataType:    "GetExtensionConfigurationSegmentData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-extension-configuration-segment",
	}),
	defineOperation("set-extension-configuration-segment", Operation{
		Name:           "Set Extension Configuration Segment",
		Method:         http.MethodPut,
		Path:           "/helix/extensions/configurations",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUnknown},
		Scopes:         []string{"unknown"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "extension_id", Type: "String", Required: true},
					{Name: "segment", Type: "String", Required: true},
					{Name: "broadcaster_id", Type: "String"},
					{Name: "content", Type: "String"},
					{Name: "version", Type: "String"},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Extensions",
			ServiceType: "ExtensionsService",
			Method:      "SetExtensionConfigurationSegment",
			Signature:   "func (s *ExtensionsService) SetExtensionConfigurationSegment(ctx context.Context, req SetExtensionConfigurationSegmentRequest) (*Response[SetExtensionConfigurationSegmentData], error)",
			RequestType: "SetExtensionConfigurationSegmentRequest",
			DataType:    "SetExtensionConfigurationSegmentData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#set-extension-configuration-segment",
	}),
	defineOperation("set-extension-required-configuration", Operation{
		Name:           "Set Extension Required Configuration",
		Method:         http.MethodPut,
		Path:           "/helix/extensions/required_configuration",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUnknown},
		Scopes:         []string{"unknown"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "extension_id", Type: "String", Required: true},
					{Name: "extension_version", Type: "String", Required: true},
					{Name: "required_configuration", Type: "String", Required: true},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Extensions",
			ServiceType: "ExtensionsService",
			Method:      "SetExtensionRequiredConfiguration",
			Signature:   "func (s *ExtensionsService) SetExtensionRequiredConfiguration(ctx context.Context, req SetExtensionRequiredConfigurationRequest) (*Response[SetExtensionRequiredConfigurationData], error)",
			RequestType: "SetExtensionRequiredConfigurationRequest",
			DataType:    "SetExtensionRequiredConfigurationData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#set-extension-required-configuration",
	}),
	defineOperation("send-extension-pubsub-message", Operation{
		Name:           "Send Extension PubSub Message",
		Method:         http.MethodPost,
		Path:           "/helix/extensions/pubsub",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUnknown},
		Scopes:         []string{"unknown"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "target", Type: "String[]", Required: true},
					{Name: "broadcaster_id", Type: "string", Required: true},
					{Name: "is_global_broadcast", Type: "Boolean"},
					{Name: "message", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{204, 400, 401, 403, 422}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Extensions",
			ServiceType: "ExtensionsService",
			Method:      "SendExtensionPubSubMessage",
			Signature:   "func (s *ExtensionsService) SendExtensionPubSubMessage(ctx context.Context, req SendExtensionPubSubMessageRequest) (*Response[SendExtensionPubSubMessageData], error)",
			RequestType: "SendExtensionPubSubMessageRequest",
			DataType:    "SendExtensionPubSubMessageData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#send-extension-pubsub-message",
	}),
	defineOperation("get-extension-live-channels", Operation{
		Name:           "Get Extension Live Channels",
		Method:         http.MethodGet,
		Path:           "/helix/extensions/live",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "extension_id", Type: "String", Required: true},
					{Name: "first", Type: "Integer"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 404}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Extensions",
			ServiceType:    "ExtensionsService",
			Method:         "GetExtensionLiveChannels",
			Signature:      "func (s *ExtensionsService) GetExtensionLiveChannels(ctx context.Context, req GetExtensionLiveChannelsRequest) (*Response[GetExtensionLiveChannelsData], error)",
			PagerSignature: pagerSignature("func (s *ExtensionsService) GetExtensionLiveChannelsPager(req GetExtensionLiveChannelsRequest, opts ...PagerOption) (*Pager[GetExtensionLiveChannelsData], error)"),
			RequestType:    "GetExtensionLiveChannelsRequest",
			DataType:       "GetExtensionLiveChannelsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-extension-live-channels",
	}),
	defineOperation("get-extension-secrets", Operation{
		Name:           "Get Extension Secrets",
		Method:         http.MethodGet,
		Path:           "/helix/extensions/jwt/secrets",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUnknown},
		Scopes:         []string{"unknown"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_paramters": {
					{Name: "extension_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Extensions",
			ServiceType: "ExtensionsService",
			Method:      "GetExtensionSecrets",
			Signature:   "func (s *ExtensionsService) GetExtensionSecrets(ctx context.Context, req GetExtensionSecretsRequest) (*Response[GetExtensionSecretsData], error)",
			RequestType: "GetExtensionSecretsRequest",
			DataType:    "GetExtensionSecretsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-extension-secrets",
	}),
	defineOperation("create-extension-secret", Operation{
		Name:           "Create Extension Secret",
		Method:         http.MethodPost,
		Path:           "/helix/extensions/jwt/secrets",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUnknown},
		Scopes:         []string{"unknown"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "extension_id", Type: "String", Required: true},
					{Name: "delay", Type: "Integer"},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Extensions",
			ServiceType: "ExtensionsService",
			Method:      "CreateExtensionSecret",
			Signature:   "func (s *ExtensionsService) CreateExtensionSecret(ctx context.Context, req CreateExtensionSecretRequest) (*Response[CreateExtensionSecretData], error)",
			RequestType: "CreateExtensionSecretRequest",
			DataType:    "CreateExtensionSecretData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#create-extension-secret",
	}),
	defineOperation("send-extension-chat-message", Operation{
		Name:           "Send Extension Chat Message",
		Method:         http.MethodPost,
		Path:           "/helix/extensions/chat",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUnknown},
		Scopes:         []string{"unknown"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "text", Type: "String", Required: true},
					{Name: "extension_id", Type: "String", Required: true},
					{Name: "extension_version", Type: "String", Required: true},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Extensions",
			ServiceType: "ExtensionsService",
			Method:      "SendExtensionChatMessage",
			Signature:   "func (s *ExtensionsService) SendExtensionChatMessage(ctx context.Context, req SendExtensionChatMessageRequest) (*Response[SendExtensionChatMessageData], error)",
			RequestType: "SendExtensionChatMessageRequest",
			DataType:    "SendExtensionChatMessageData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#send-extension-chat-message",
	}),
	defineOperation("get-extensions", Operation{
		Name:           "Get Extensions",
		Method:         http.MethodGet,
		Path:           "/helix/extensions",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUnknown},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "extension_id", Type: "String", Required: true},
					{Name: "extension_version", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Extensions",
			ServiceType: "ExtensionsService",
			Method:      "GetExtensions",
			Signature:   "func (s *ExtensionsService) GetExtensions(ctx context.Context, req GetExtensionsRequest) (*Response[GetExtensionsData], error)",
			RequestType: "GetExtensionsRequest",
			DataType:    "GetExtensionsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-extensions",
	}),
	defineOperation("get-released-extensions", Operation{
		Name:           "Get Released Extensions",
		Method:         http.MethodGet,
		Path:           "/helix/extensions/released",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "extension_id", Type: "String", Required: true},
					{Name: "extension_version", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Extensions",
			ServiceType: "ExtensionsService",
			Method:      "GetReleasedExtensions",
			Signature:   "func (s *ExtensionsService) GetReleasedExtensions(ctx context.Context, req GetReleasedExtensionsRequest) (*Response[GetReleasedExtensionsData], error)",
			RequestType: "GetReleasedExtensionsRequest",
			DataType:    "GetReleasedExtensionsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-released-extensions",
	}),
	defineOperation("get-extension-bits-products", Operation{
		Name:           "Get Extension Bits Products",
		Method:         http.MethodGet,
		Path:           "/helix/bits/extensions",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "should_include_all", Type: "Boolean"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Extensions",
			ServiceType: "ExtensionsService",
			Method:      "GetExtensionBitsProducts",
			Signature:   "func (s *ExtensionsService) GetExtensionBitsProducts(ctx context.Context, req GetExtensionBitsProductsRequest) (*Response[GetExtensionBitsProductsData], error)",
			RequestType: "GetExtensionBitsProductsRequest",
			DataType:    "GetExtensionBitsProductsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-extension-bits-products",
	}),
	defineOperation("update-extension-bits-product", Operation{
		Name:           "Update Extension Bits Product",
		Method:         http.MethodPut,
		Path:           "/helix/bits/extensions",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body_parameters": {
					{Name: "sku", Type: "String", Required: true},
					{Name: "cost", Type: "Object", Required: true},
					{Name: "amount", Type: "Integer", Required: true},
					{Name: "type", Type: "String", Required: true},
					{Name: "display_name", Type: "String", Required: true},
					{Name: "in_development", Type: "Boolean"},
					{Name: "expiration", Type: "String"},
					{Name: "is_broadcast", Type: "Boolean"},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Extensions",
			ServiceType: "ExtensionsService",
			Method:      "UpdateExtensionBitsProduct",
			Signature:   "func (s *ExtensionsService) UpdateExtensionBitsProduct(ctx context.Context, req UpdateExtensionBitsProductRequest) (*Response[UpdateExtensionBitsProductData], error)",
			RequestType: "UpdateExtensionBitsProductRequest",
			DataType:    "UpdateExtensionBitsProductData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-extension-bits-product",
	}),
)
