package manifest

import "net/http"

var channelPointsOperations = operationsForGroup("Channel Points",
	defineOperation("create-custom-rewards", Operation{
		Name:           "Create Custom Rewards",
		Method:         http.MethodPost,
		Path:           "/helix/channel_points/custom_rewards",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:redemptions"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "title", Type: "String", Required: true},
					{Name: "cost", Type: "Int64", Required: true},
					{Name: "prompt", Type: "String"},
					{Name: "is_enabled", Type: "Boolean"},
					{Name: "background_color", Type: "String"},
					{Name: "is_user_input_required", Type: "Boolean"},
					{Name: "is_max_per_stream_enabled", Type: "Boolean"},
					{Name: "max_per_stream", Type: "Integer"},
					{Name: "is_max_per_user_per_stream_enabled", Type: "Boolean"},
					{Name: "max_per_user_per_stream", Type: "Integer"},
					{Name: "is_global_cooldown_enabled", Type: "Boolean"},
					{Name: "global_cooldown_seconds", Type: "Integer"},
					{Name: "should_redemptions_skip_request_queue", Type: "Boolean"},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 500}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.ChannelPoints",
			ServiceType: "ChannelPointsService",
			Method:      "CreateCustomRewards",
			Signature:   "func (s *ChannelPointsService) CreateCustomRewards(ctx context.Context, req CreateCustomRewardsRequest) (*Response[CreateCustomRewardsData], error)",
			RequestType: "CreateCustomRewardsRequest",
			DataType:    "CreateCustomRewardsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#create-custom-rewards",
	}),
	defineOperation("delete-custom-reward", Operation{
		Name:           "Delete Custom Reward",
		Method:         http.MethodDelete,
		Path:           "/helix/channel_points/custom_rewards",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:redemptions"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 403, 404, 500}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.ChannelPoints",
			ServiceType: "ChannelPointsService",
			Method:      "DeleteCustomReward",
			Signature:   "func (s *ChannelPointsService) DeleteCustomReward(ctx context.Context, req DeleteCustomRewardRequest) (*Response[DeleteCustomRewardData], error)",
			RequestType: "DeleteCustomRewardRequest",
			DataType:    "DeleteCustomRewardData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#delete-custom-reward",
	}),
	defineOperation("get-custom-reward", Operation{
		Name:           "Get Custom Reward",
		Method:         http.MethodGet,
		Path:           "/helix/channel_points/custom_rewards",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:read:redemptions", "channel:manage:redemptions"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "id", Type: "String"},
					{Name: "only_manageable_rewards", Type: "Boolean"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 404, 500}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.ChannelPoints",
			ServiceType: "ChannelPointsService",
			Method:      "GetCustomReward",
			Signature:   "func (s *ChannelPointsService) GetCustomReward(ctx context.Context, req GetCustomRewardRequest) (*Response[GetCustomRewardData], error)",
			RequestType: "GetCustomRewardRequest",
			DataType:    "GetCustomRewardData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-custom-reward",
	}),
	defineOperation("get-custom-reward-redemption", Operation{
		Name:           "Get Custom Reward Redemption",
		Method:         http.MethodGet,
		Path:           "/helix/channel_points/custom_rewards/redemptions",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:read:redemptions", "channel:manage:redemptions"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "reward_id", Type: "String", Required: true},
					{Name: "status", Type: "String", Required: true},
					{Name: "id", Type: "String"},
					{Name: "sort", Type: "String"},
					{Name: "after", Type: "String"},
					{Name: "first", Type: "Integer"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 404, 500}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.ChannelPoints",
			ServiceType:    "ChannelPointsService",
			Method:         "GetCustomRewardRedemption",
			Signature:      "func (s *ChannelPointsService) GetCustomRewardRedemption(ctx context.Context, req GetCustomRewardRedemptionRequest) (*Response[GetCustomRewardRedemptionData], error)",
			PagerSignature: pagerSignature("func (s *ChannelPointsService) GetCustomRewardRedemptionPager(req GetCustomRewardRedemptionRequest, opts ...PagerOption) (*Pager[GetCustomRewardRedemptionData], error)"),
			RequestType:    "GetCustomRewardRedemptionRequest",
			DataType:       "GetCustomRewardRedemptionData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-custom-reward-redemption",
	}),
	defineOperation("update-custom-reward", Operation{
		Name:           "Update Custom Reward",
		Method:         http.MethodPatch,
		Path:           "/helix/channel_points/custom_rewards",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:redemptions"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "title", Type: "String"},
					{Name: "prompt", Type: "String"},
					{Name: "cost", Type: "Int64"},
					{Name: "background_color", Type: "String"},
					{Name: "is_enabled", Type: "Boolean"},
					{Name: "is_user_input_required", Type: "Boolean"},
					{Name: "is_max_per_stream_enabled", Type: "Boolean"},
					{Name: "max_per_stream", Type: "Int64"},
					{Name: "is_max_per_user_per_stream_enabled", Type: "Boolean"},
					{Name: "max_per_user_per_stream", Type: "Int64"},
					{Name: "is_global_cooldown_enabled", Type: "Boolean"},
					{Name: "global_cooldown_seconds", Type: "Int64"},
					{Name: "is_paused", Type: "Boolean"},
					{Name: "should_redemptions_skip_request_queue", Type: "Boolean"},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 404, 500}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.ChannelPoints",
			ServiceType: "ChannelPointsService",
			Method:      "UpdateCustomReward",
			Signature:   "func (s *ChannelPointsService) UpdateCustomReward(ctx context.Context, req UpdateCustomRewardRequest) (*Response[UpdateCustomRewardData], error)",
			RequestType: "UpdateCustomRewardRequest",
			DataType:    "UpdateCustomRewardData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-custom-reward",
	}),
	defineOperation("update-redemption-status", Operation{
		Name:           "Update Redemption Status",
		Method:         http.MethodPatch,
		Path:           "/helix/channel_points/custom_rewards/redemptions",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:redemptions"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "status", Type: "String", Required: true},
				},
				"query_parameters": {
					{Name: "id", Type: "String", Required: true},
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "reward_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 404, 500}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.ChannelPoints",
			ServiceType: "ChannelPointsService",
			Method:      "UpdateRedemptionStatus",
			Signature:   "func (s *ChannelPointsService) UpdateRedemptionStatus(ctx context.Context, req UpdateRedemptionStatusRequest) (*Response[UpdateRedemptionStatusData], error)",
			RequestType: "UpdateRedemptionStatusRequest",
			DataType:    "UpdateRedemptionStatusData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-redemption-status",
	}),
)
