package manifest

import "net/http"

var guestStarOperations = operationsForGroup("Guest Star",
	defineOperation("get-channel-guest-star-settings", Operation{
		Name:           "Get Channel Guest Star Settings",
		Method:         http.MethodGet,
		Path:           "/helix/guest_star/channel_settings",
		Stability:      StabilityBeta,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:read:guest_star", "channel:manage:guest_star", "moderator:read:guest_star", "moderator:manage:guest_star"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.GuestStar",
			ServiceType: "ExperimentalGuestStarService",
			Method:      "GetChannelGuestStarSettings",
			Signature:   "func (s *ExperimentalGuestStarService) GetChannelGuestStarSettings(ctx context.Context, req GetChannelGuestStarSettingsRequest) (*Response[GetChannelGuestStarSettingsData], error)",
			RequestType: "GetChannelGuestStarSettingsRequest",
			DataType:    "GetChannelGuestStarSettingsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-channel-guest-star-settings",
	}),
	defineOperation("update-channel-guest-star-settings", Operation{
		Name:           "Update Channel Guest Star Settings",
		Method:         http.MethodPut,
		Path:           "/helix/guest_star/channel_settings",
		Stability:      StabilityBeta,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:guest_star"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "is_moderator_send_live_enabled", Type: "Boolean"},
					{Name: "slot_count", Type: "Integer"},
					{Name: "is_browser_source_audio_enabled", Type: "Boolean"},
					{Name: "group_layout", Type: "String"},
					{Name: "regenerate_browser_sources", Type: "Boolean"},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.GuestStar",
			ServiceType: "ExperimentalGuestStarService",
			Method:      "UpdateChannelGuestStarSettings",
			Signature:   "func (s *ExperimentalGuestStarService) UpdateChannelGuestStarSettings(ctx context.Context, req UpdateChannelGuestStarSettingsRequest) (*Response[UpdateChannelGuestStarSettingsData], error)",
			RequestType: "UpdateChannelGuestStarSettingsRequest",
			DataType:    "UpdateChannelGuestStarSettingsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-channel-guest-star-settings",
	}),
	defineOperation("get-guest-star-session", Operation{
		Name:           "Get Guest Star Session",
		Method:         http.MethodGet,
		Path:           "/helix/guest_star/session",
		Stability:      StabilityBeta,
		TokenClasses:   []TokenClass{TokenClassUnknown},
		Scopes:         []string{"channel:read:guest_star", "channel:manage:guest_star", "moderator:read:guest_star", "moderator:manage:guest_star"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.GuestStar",
			ServiceType: "ExperimentalGuestStarService",
			Method:      "GetGuestStarSession",
			Signature:   "func (s *ExperimentalGuestStarService) GetGuestStarSession(ctx context.Context, req GetGuestStarSessionRequest) (*Response[GetGuestStarSessionData], error)",
			RequestType: "GetGuestStarSessionRequest",
			DataType:    "GetGuestStarSessionData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-guest-star-session",
	}),
	defineOperation("create-guest-star-session", Operation{
		Name:           "Create Guest Star Session",
		Method:         http.MethodPost,
		Path:           "/helix/guest_star/session",
		Stability:      StabilityBeta,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:guest_star"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 409}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.GuestStar",
			ServiceType: "ExperimentalGuestStarService",
			Method:      "CreateGuestStarSession",
			Signature:   "func (s *ExperimentalGuestStarService) CreateGuestStarSession(ctx context.Context, req CreateGuestStarSessionRequest) (*Response[CreateGuestStarSessionData], error)",
			RequestType: "CreateGuestStarSessionRequest",
			DataType:    "CreateGuestStarSessionData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#create-guest-star-session",
	}),
	defineOperation("end-guest-star-session", Operation{
		Name:           "End Guest Star Session",
		Method:         http.MethodDelete,
		Path:           "/helix/guest_star/session",
		Stability:      StabilityBeta,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:guest_star"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "session_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.GuestStar",
			ServiceType: "ExperimentalGuestStarService",
			Method:      "EndGuestStarSession",
			Signature:   "func (s *ExperimentalGuestStarService) EndGuestStarSession(ctx context.Context, req EndGuestStarSessionRequest) (*Response[EndGuestStarSessionData], error)",
			RequestType: "EndGuestStarSessionRequest",
			DataType:    "EndGuestStarSessionData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#end-guest-star-session",
	}),
	defineOperation("get-guest-star-invites", Operation{
		Name:           "Get Guest Star Invites",
		Method:         http.MethodGet,
		Path:           "/helix/guest_star/invites",
		Stability:      StabilityBeta,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:read:guest_star", "channel:manage:guest_star", "moderator:read:guest_star", "moderator:manage:guest_star"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "session_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 403, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.GuestStar",
			ServiceType: "ExperimentalGuestStarService",
			Method:      "GetGuestStarInvites",
			Signature:   "func (s *ExperimentalGuestStarService) GetGuestStarInvites(ctx context.Context, req GetGuestStarInvitesRequest) (*Response[GetGuestStarInvitesData], error)",
			RequestType: "GetGuestStarInvitesRequest",
			DataType:    "GetGuestStarInvitesData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-guest-star-invites",
	}),
	defineOperation("send-guest-star-invite", Operation{
		Name:           "Send Guest Star Invite",
		Method:         http.MethodPost,
		Path:           "/helix/guest_star/invites",
		Stability:      StabilityBeta,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:guest_star", "moderator:manage:guest_star"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "session_id", Type: "String", Required: true},
					{Name: "guest_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.GuestStar",
			ServiceType: "ExperimentalGuestStarService",
			Method:      "SendGuestStarInvite",
			Signature:   "func (s *ExperimentalGuestStarService) SendGuestStarInvite(ctx context.Context, req SendGuestStarInviteRequest) (*Response[SendGuestStarInviteData], error)",
			RequestType: "SendGuestStarInviteRequest",
			DataType:    "SendGuestStarInviteData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#send-guest-star-invite",
	}),
	defineOperation("delete-guest-star-invite", Operation{
		Name:           "Delete Guest Star Invite",
		Method:         http.MethodDelete,
		Path:           "/helix/guest_star/invites",
		Stability:      StabilityBeta,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:guest_star", "moderator:manage:guest_star"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "session_id", Type: "String", Required: true},
					{Name: "guest_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 403, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.GuestStar",
			ServiceType: "ExperimentalGuestStarService",
			Method:      "DeleteGuestStarInvite",
			Signature:   "func (s *ExperimentalGuestStarService) DeleteGuestStarInvite(ctx context.Context, req DeleteGuestStarInviteRequest) (*Response[DeleteGuestStarInviteData], error)",
			RequestType: "DeleteGuestStarInviteRequest",
			DataType:    "DeleteGuestStarInviteData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#delete-guest-star-invite",
	}),
	defineOperation("assign-guest-star-slot", Operation{
		Name:           "Assign Guest Star Slot",
		Method:         http.MethodPost,
		Path:           "/helix/guest_star/slot",
		Stability:      StabilityBeta,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:guest_star", "moderator:manage:guest_star"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "session_id", Type: "String", Required: true},
					{Name: "guest_id", Type: "String", Required: true},
					{Name: "slot_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{204, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.GuestStar",
			ServiceType: "ExperimentalGuestStarService",
			Method:      "AssignGuestStarSlot",
			Signature:   "func (s *ExperimentalGuestStarService) AssignGuestStarSlot(ctx context.Context, req AssignGuestStarSlotRequest) (*Response[AssignGuestStarSlotData], error)",
			RequestType: "AssignGuestStarSlotRequest",
			DataType:    "AssignGuestStarSlotData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#assign-guest-star-slot",
	}),
	defineOperation("update-guest-star-slot", Operation{
		Name:           "Update Guest Star Slot",
		Method:         http.MethodPatch,
		Path:           "/helix/guest_star/slot",
		Stability:      StabilityBeta,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:guest_star", "moderator:manage:guest_star"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "session_id", Type: "String", Required: true},
					{Name: "source_slot_id", Type: "String", Required: true},
					{Name: "destination_slot_id", Type: "String"},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.GuestStar",
			ServiceType: "ExperimentalGuestStarService",
			Method:      "UpdateGuestStarSlot",
			Signature:   "func (s *ExperimentalGuestStarService) UpdateGuestStarSlot(ctx context.Context, req UpdateGuestStarSlotRequest) (*Response[UpdateGuestStarSlotData], error)",
			RequestType: "UpdateGuestStarSlotRequest",
			DataType:    "UpdateGuestStarSlotData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-guest-star-slot",
	}),
	defineOperation("delete-guest-star-slot", Operation{
		Name:           "Delete Guest Star Slot",
		Method:         http.MethodDelete,
		Path:           "/helix/guest_star/slot",
		Stability:      StabilityBeta,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:guest_star", "moderator:manage:guest_star"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "session_id", Type: "String", Required: true},
					{Name: "guest_id", Type: "String", Required: true},
					{Name: "slot_id", Type: "String", Required: true},
					{Name: "should_reinvite_guest", Type: "String"},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 403, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.GuestStar",
			ServiceType: "ExperimentalGuestStarService",
			Method:      "DeleteGuestStarSlot",
			Signature:   "func (s *ExperimentalGuestStarService) DeleteGuestStarSlot(ctx context.Context, req DeleteGuestStarSlotRequest) (*Response[DeleteGuestStarSlotData], error)",
			RequestType: "DeleteGuestStarSlotRequest",
			DataType:    "DeleteGuestStarSlotData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#delete-guest-star-slot",
	}),
	defineOperation("update-guest-star-slot-settings", Operation{
		Name:           "Update Guest Star Slot Settings",
		Method:         http.MethodPatch,
		Path:           "/helix/guest_star/slot_settings",
		Stability:      StabilityBeta,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:guest_star", "moderator:manage:guest_star"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "session_id", Type: "String", Required: true},
					{Name: "slot_id", Type: "String", Required: true},
					{Name: "is_audio_enabled", Type: "Boolean"},
					{Name: "is_video_enabled", Type: "Boolean"},
					{Name: "is_live", Type: "Boolean"},
					{Name: "volume", Type: "Integer"},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.GuestStar",
			ServiceType: "ExperimentalGuestStarService",
			Method:      "UpdateGuestStarSlotSettings",
			Signature:   "func (s *ExperimentalGuestStarService) UpdateGuestStarSlotSettings(ctx context.Context, req UpdateGuestStarSlotSettingsRequest) (*Response[UpdateGuestStarSlotSettingsData], error)",
			RequestType: "UpdateGuestStarSlotSettingsRequest",
			DataType:    "UpdateGuestStarSlotSettingsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-guest-star-slot-settings",
	}),
)
