package manifest

import "net/http"

var usersOperations = operationsForGroup("Users",
	defineOperation("get-users", Operation{
		Name:           "Get Users",
		Method:         http.MethodGet,
		Path:           "/helix/users",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "id", Type: "String"},
					{Name: "login", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Users",
			ServiceType: "UsersService",
			Method:      "GetUsers",
			Signature:   "func (s *UsersService) GetUsers(ctx context.Context, req GetUsersRequest) (*Response[GetUsersData], error)",
			RequestType: "GetUsersRequest",
			DataType:    "GetUsersData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-users",
	}),
	defineOperation("update-user", Operation{
		Name:           "Update User",
		Method:         http.MethodPut,
		Path:           "/helix/users",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"user:edit"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "description", Type: "string"},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Users",
			ServiceType: "UsersService",
			Method:      "UpdateUser",
			Signature:   "func (s *UsersService) UpdateUser(ctx context.Context, req UpdateUserRequest) (*Response[UpdateUserData], error)",
			RequestType: "UpdateUserRequest",
			DataType:    "UpdateUserData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-user",
	}),
	defineOperation("get-authorization-by-user", Operation{
		Name:           "Get Authorization By User",
		Method:         http.MethodGet,
		Path:           "/helix/authorization/users",
		Stability:      StabilityNew,
		TokenClasses:   []TokenClass{TokenClassApp},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 500}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.Users",
			ServiceType: "ExperimentalUsersService",
			Method:      "GetAuthorizationByUser",
			Signature:   "func (s *ExperimentalUsersService) GetAuthorizationByUser(ctx context.Context, req GetAuthorizationByUserRequest) (*Response[GetAuthorizationByUserData], error)",
			RequestType: "GetAuthorizationByUserRequest",
			DataType:    "GetAuthorizationByUserData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-authorization-by-user",
	}),
	defineOperation("get-user-block-list", Operation{
		Name:           "Get User Block List",
		Method:         http.MethodGet,
		Path:           "/helix/users/blocks",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"user:read:blocked_users"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "first", Type: "Integer"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Users",
			ServiceType:    "UsersService",
			Method:         "GetUserBlockList",
			Signature:      "func (s *UsersService) GetUserBlockList(ctx context.Context, req GetUserBlockListRequest) (*Response[GetUserBlockListData], error)",
			PagerSignature: pagerSignature("func (s *UsersService) GetUserBlockListPager(req GetUserBlockListRequest, opts ...PagerOption) (*Pager[GetUserBlockListData], error)"),
			RequestType:    "GetUserBlockListRequest",
			DataType:       "GetUserBlockListData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-user-block-list",
	}),
	defineOperation("block-user", Operation{
		Name:           "Block User",
		Method:         http.MethodPut,
		Path:           "/helix/users/blocks",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"user:manage:blocked_users"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "target_user_id", Type: "String", Required: true},
					{Name: "source_context", Type: "String"},
					{Name: "reason", Type: "String"},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Users",
			ServiceType: "UsersService",
			Method:      "BlockUser",
			Signature:   "func (s *UsersService) BlockUser(ctx context.Context, req BlockUserRequest) (*Response[BlockUserData], error)",
			RequestType: "BlockUserRequest",
			DataType:    "BlockUserData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#block-user",
	}),
	defineOperation("unblock-user", Operation{
		Name:           "Unblock User",
		Method:         http.MethodDelete,
		Path:           "/helix/users/blocks",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"user:manage:blocked_users"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "target_user_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Users",
			ServiceType: "UsersService",
			Method:      "UnblockUser",
			Signature:   "func (s *UsersService) UnblockUser(ctx context.Context, req UnblockUserRequest) (*Response[UnblockUserData], error)",
			RequestType: "UnblockUserRequest",
			DataType:    "UnblockUserData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#unblock-user",
	}),
	defineOperation("get-user-extensions", Operation{
		Name:           "Get User Extensions",
		Method:         http.MethodGet,
		Path:           "/helix/users/extensions/list",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"user:read:broadcast", "user:edit:broadcast"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"unknown": {},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Users",
			ServiceType: "UsersService",
			Method:      "GetUserExtensions",
			Signature:   "func (s *UsersService) GetUserExtensions(ctx context.Context, req GetUserExtensionsRequest) (*Response[GetUserExtensionsData], error)",
			RequestType: "GetUserExtensionsRequest",
			DataType:    "GetUserExtensionsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-user-extensions",
	}),
	defineOperation("get-user-active-extensions", Operation{
		Name:           "Get User Active Extensions",
		Method:         http.MethodGet,
		Path:           "/helix/users/extensions",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Users",
			ServiceType: "UsersService",
			Method:      "GetUserActiveExtensions",
			Signature:   "func (s *UsersService) GetUserActiveExtensions(ctx context.Context, req GetUserActiveExtensionsRequest) (*Response[GetUserActiveExtensionsData], error)",
			RequestType: "GetUserActiveExtensionsRequest",
			DataType:    "GetUserActiveExtensionsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-user-active-extensions",
	}),
	defineOperation("update-user-extensions", Operation{
		Name:           "Update User Extensions",
		Method:         http.MethodPut,
		Path:           "/helix/users/extensions",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"user:edit:broadcast"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "data", Type: "map[string]string", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Users",
			ServiceType: "UsersService",
			Method:      "UpdateUserExtensions",
			Signature:   "func (s *UsersService) UpdateUserExtensions(ctx context.Context, req UpdateUserExtensionsRequest) (*Response[UpdateUserExtensionsData], error)",
			RequestType: "UpdateUserExtensionsRequest",
			DataType:    "UpdateUserExtensionsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-user-extensions",
	}),
)
