package manifest

import "net/http"

var conduitsOperations = operationsForGroup("Conduits",
	defineOperation("get-conduits", Operation{
		Name:           "Get Conduits",
		Method:         http.MethodGet,
		Path:           "/helix/eventsub/conduits",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"unknown": {},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Conduits",
			ServiceType: "ConduitsService",
			Method:      "GetConduits",
			Signature:   "func (s *ConduitsService) GetConduits(ctx context.Context, req GetConduitsRequest) (*Response[GetConduitsData], error)",
			RequestType: "GetConduitsRequest",
			DataType:    "GetConduitsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-conduits",
	}),
	defineOperation("create-conduits", Operation{
		Name:           "Create Conduits",
		Method:         http.MethodPost,
		Path:           "/helix/eventsub/conduits",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "shard_count", Type: "Integer", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Conduits",
			ServiceType: "ConduitsService",
			Method:      "CreateConduits",
			Signature:   "func (s *ConduitsService) CreateConduits(ctx context.Context, req CreateConduitsRequest) (*Response[CreateConduitsData], error)",
			RequestType: "CreateConduitsRequest",
			DataType:    "CreateConduitsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#create-conduits",
	}),
	defineOperation("update-conduits", Operation{
		Name:           "Update Conduits",
		Method:         http.MethodPatch,
		Path:           "/helix/eventsub/conduits",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "id", Type: "String", Required: true},
					{Name: "shard_count", Type: "Integer", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Conduits",
			ServiceType: "ConduitsService",
			Method:      "UpdateConduits",
			Signature:   "func (s *ConduitsService) UpdateConduits(ctx context.Context, req UpdateConduitsRequest) (*Response[UpdateConduitsData], error)",
			RequestType: "UpdateConduitsRequest",
			DataType:    "UpdateConduitsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-conduits",
	}),
	defineOperation("delete-conduit", Operation{
		Name:           "Delete Conduit",
		Method:         http.MethodDelete,
		Path:           "/helix/eventsub/conduits",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Conduits",
			ServiceType: "ConduitsService",
			Method:      "DeleteConduit",
			Signature:   "func (s *ConduitsService) DeleteConduit(ctx context.Context, req DeleteConduitRequest) (*Response[DeleteConduitData], error)",
			RequestType: "DeleteConduitRequest",
			DataType:    "DeleteConduitData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#delete-conduit",
	}),
	defineOperation("get-conduit-shards", Operation{
		Name:           "Get Conduit Shards",
		Method:         http.MethodGet,
		Path:           "/helix/eventsub/conduits/shards",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "conduit_id", Type: "String", Required: true},
					{Name: "status", Type: "String"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 404}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Conduits",
			ServiceType:    "ConduitsService",
			Method:         "GetConduitShards",
			Signature:      "func (s *ConduitsService) GetConduitShards(ctx context.Context, req GetConduitShardsRequest) (*Response[GetConduitShardsData], error)",
			PagerSignature: pagerSignature("func (s *ConduitsService) GetConduitShardsPager(req GetConduitShardsRequest, opts ...PagerOption) (*Pager[GetConduitShardsData], error)"),
			RequestType:    "GetConduitShardsRequest",
			DataType:       "GetConduitShardsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-conduit-shards",
	}),
	defineOperation("update-conduit-shards", Operation{
		Name:           "Update Conduit Shards",
		Method:         http.MethodPatch,
		Path:           "/helix/eventsub/conduits/shards",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "conduit_id", Type: "String", Required: true},
					{Name: "shards", Type: "Object[]", Required: true},
					{Name: "id", Type: "String", Required: true},
					{Name: "transport", Type: "Object", Required: true},
					{Name: "method", Type: "String"},
					{Name: "callback", Type: "String"},
					{Name: "secret", Type: "String"},
					{Name: "session_id", Type: "String"},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{202, 400, 401, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Conduits",
			ServiceType: "ConduitsService",
			Method:      "UpdateConduitShards",
			Signature:   "func (s *ConduitsService) UpdateConduitShards(ctx context.Context, req UpdateConduitShardsRequest) (*Response[UpdateConduitShardsData], error)",
			RequestType: "UpdateConduitShardsRequest",
			DataType:    "UpdateConduitShardsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-conduit-shards",
	}),
)
