package manifest

import "net/http"

var streamsOperations = operationsForGroup("Streams",
	defineOperation("get-stream-key", Operation{
		Name:           "Get Stream Key",
		Method:         http.MethodGet,
		Path:           "/helix/streams/key",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:read:stream_key"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Streams",
			ServiceType: "StreamsService",
			Method:      "GetStreamKey",
			Signature:   "func (s *StreamsService) GetStreamKey(ctx context.Context, req GetStreamKeyRequest) (*Response[GetStreamKeyData], error)",
			RequestType: "GetStreamKeyRequest",
			DataType:    "GetStreamKeyData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-stream-key",
	}),
	defineOperation("get-streams", Operation{
		Name:           "Get Streams",
		Method:         http.MethodGet,
		Path:           "/helix/streams",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String"},
					{Name: "user_login", Type: "String"},
					{Name: "game_id", Type: "String"},
					{Name: "type", Type: "String"},
					{Name: "language", Type: "String"},
					{Name: "first", Type: "Integer"},
					{Name: "before", Type: "String"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Streams",
			ServiceType:    "StreamsService",
			Method:         "GetStreams",
			Signature:      "func (s *StreamsService) GetStreams(ctx context.Context, req GetStreamsRequest) (*Response[GetStreamsData], error)",
			PagerSignature: pagerSignature("func (s *StreamsService) GetStreamsPager(req GetStreamsRequest, opts ...PagerOption) (*Pager[GetStreamsData], error)"),
			RequestType:    "GetStreamsRequest",
			DataType:       "GetStreamsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-streams",
	}),
	defineOperation("get-followed-streams", Operation{
		Name:           "Get Followed Streams",
		Method:         http.MethodGet,
		Path:           "/helix/streams/followed",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"user:read:follows"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String", Required: true},
					{Name: "first", Type: "Integer"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Streams",
			ServiceType:    "StreamsService",
			Method:         "GetFollowedStreams",
			Signature:      "func (s *StreamsService) GetFollowedStreams(ctx context.Context, req GetFollowedStreamsRequest) (*Response[GetFollowedStreamsData], error)",
			PagerSignature: pagerSignature("func (s *StreamsService) GetFollowedStreamsPager(req GetFollowedStreamsRequest, opts ...PagerOption) (*Pager[GetFollowedStreamsData], error)"),
			RequestType:    "GetFollowedStreamsRequest",
			DataType:       "GetFollowedStreamsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-followed-streams",
	}),
	defineOperation("create-stream-marker", Operation{
		Name:           "Create Stream Marker",
		Method:         http.MethodPost,
		Path:           "/helix/streams/markers",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:broadcast"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "user_id", Type: "String", Required: true},
					{Name: "description", Type: "String"},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Streams",
			ServiceType: "StreamsService",
			Method:      "CreateStreamMarker",
			Signature:   "func (s *StreamsService) CreateStreamMarker(ctx context.Context, req CreateStreamMarkerRequest) (*Response[CreateStreamMarkerData], error)",
			RequestType: "CreateStreamMarkerRequest",
			DataType:    "CreateStreamMarkerData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#create-stream-marker",
	}),
	defineOperation("get-stream-markers", Operation{
		Name:           "Get Stream Markers",
		Method:         http.MethodGet,
		Path:           "/helix/streams/markers",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"user:read:broadcast", "channel:manage:broadcast"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameter": {
					{Name: "user_id", Type: "String", Required: true},
					{Name: "video_id", Type: "String", Required: true},
					{Name: "first", Type: "String"},
					{Name: "before", Type: "String"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 404}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Streams",
			ServiceType:    "StreamsService",
			Method:         "GetStreamMarkers",
			Signature:      "func (s *StreamsService) GetStreamMarkers(ctx context.Context, req GetStreamMarkersRequest) (*Response[GetStreamMarkersData], error)",
			PagerSignature: pagerSignature("func (s *StreamsService) GetStreamMarkersPager(req GetStreamMarkersRequest, opts ...PagerOption) (*Pager[GetStreamMarkersData], error)"),
			RequestType:    "GetStreamMarkersRequest",
			DataType:       "GetStreamMarkersData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-stream-markers",
	}),
)
