package manifest

import "net/http"

var channelsOperations = operationsForGroup("Channels",
	defineOperation("get-channel-information", Operation{
		Name:           "Get Channel Information",
		Method:         http.MethodGet,
		Path:           "/helix/channels",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 429, 500}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Channels",
			ServiceType: "ChannelsService",
			Method:      "GetChannelInformation",
			Signature:   "func (s *ChannelsService) GetChannelInformation(ctx context.Context, req GetChannelInformationRequest) (*Response[GetChannelInformationData], error)",
			RequestType: "GetChannelInformationRequest",
			DataType:    "GetChannelInformationData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-channel-information",
	}),
	defineOperation("modify-channel-information", Operation{
		Name:           "Modify Channel Information",
		Method:         http.MethodPatch,
		Path:           "/helix/channels",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:broadcast"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "game_id", Type: "String"},
					{Name: "broadcaster_language", Type: "String"},
					{Name: "title", Type: "String"},
					{Name: "delay", Type: "Integer"},
					{Name: "tags", Type: "String[]"},
					{Name: "content_classification_labels", Type: "Label[]"},
					{Name: "id", Type: "string", Required: true},
					{Name: "is_enabled", Type: "boolean", Required: true},
					{Name: "is_branded_content", Type: "Boolean"},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 403, 409, 500}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Channels",
			ServiceType: "ChannelsService",
			Method:      "ModifyChannelInformation",
			Signature:   "func (s *ChannelsService) ModifyChannelInformation(ctx context.Context, req ModifyChannelInformationRequest) (*Response[ModifyChannelInformationData], error)",
			RequestType: "ModifyChannelInformationRequest",
			DataType:    "ModifyChannelInformationData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#modify-channel-information",
	}),
	defineOperation("get-channel-editors", Operation{
		Name:           "Get Channel Editors",
		Method:         http.MethodGet,
		Path:           "/helix/channels/editors",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:read:editors"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Channels",
			ServiceType: "ChannelsService",
			Method:      "GetChannelEditors",
			Signature:   "func (s *ChannelsService) GetChannelEditors(ctx context.Context, req GetChannelEditorsRequest) (*Response[GetChannelEditorsData], error)",
			RequestType: "GetChannelEditorsRequest",
			DataType:    "GetChannelEditorsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-channel-editors",
	}),
	defineOperation("get-followed-channels", Operation{
		Name:           "Get Followed Channels",
		Method:         http.MethodGet,
		Path:           "/helix/channels/followed",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"user:read:follows"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String", Required: true},
					{Name: "broadcaster_id", Type: "String"},
					{Name: "first", Type: "Integer"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Channels",
			ServiceType:    "ChannelsService",
			Method:         "GetFollowedChannels",
			Signature:      "func (s *ChannelsService) GetFollowedChannels(ctx context.Context, req GetFollowedChannelsRequest) (*Response[GetFollowedChannelsData], error)",
			PagerSignature: pagerSignature("func (s *ChannelsService) GetFollowedChannelsPager(req GetFollowedChannelsRequest, opts ...PagerOption) (*Pager[GetFollowedChannelsData], error)"),
			RequestType:    "GetFollowedChannelsRequest",
			DataType:       "GetFollowedChannelsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-followed-channels",
	}),
	defineOperation("get-channel-followers", Operation{
		Name:           "Get Channel Followers",
		Method:         http.MethodGet,
		Path:           "/helix/channels/followers",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"moderator:read:followers"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String"},
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "first", Type: "Integer"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Channels",
			ServiceType:    "ChannelsService",
			Method:         "GetChannelFollowers",
			Signature:      "func (s *ChannelsService) GetChannelFollowers(ctx context.Context, req GetChannelFollowersRequest) (*Response[GetChannelFollowersData], error)",
			PagerSignature: pagerSignature("func (s *ChannelsService) GetChannelFollowersPager(req GetChannelFollowersRequest, opts ...PagerOption) (*Pager[GetChannelFollowersData], error)"),
			RequestType:    "GetChannelFollowersRequest",
			DataType:       "GetChannelFollowersData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-channel-followers",
	}),
)
