package manifest

import "net/http"

var scheduleOperations = operationsForGroup("Schedule",
	defineOperation("get-channel-stream-schedule", Operation{
		Name:           "Get Channel Stream Schedule",
		Method:         http.MethodGet,
		Path:           "/helix/schedule",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "id", Type: "String"},
					{Name: "start_time", Type: "String"},
					{Name: "utc_offset", Type: "String"},
					{Name: "first", Type: "Integer"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 404}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Schedule",
			ServiceType:    "ScheduleService",
			Method:         "GetChannelStreamSchedule",
			Signature:      "func (s *ScheduleService) GetChannelStreamSchedule(ctx context.Context, req GetChannelStreamScheduleRequest) (*Response[GetChannelStreamScheduleData], error)",
			PagerSignature: pagerSignature("func (s *ScheduleService) GetChannelStreamSchedulePager(req GetChannelStreamScheduleRequest, opts ...PagerOption) (*Pager[GetChannelStreamScheduleData], error)"),
			RequestType:    "GetChannelStreamScheduleRequest",
			DataType:       "GetChannelStreamScheduleData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-channel-stream-schedule",
	}),
	defineOperation("get-channel-icalendar", Operation{
		Name:           "Get Channel iCalendar",
		Method:         http.MethodGet,
		Path:           "/helix/schedule/icalendar",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUnknown},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "text", Status: []int{200, 400}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Schedule",
			ServiceType: "ScheduleService",
			Method:      "GetChannelICalendar",
			Signature:   "func (s *ScheduleService) GetChannelICalendar(ctx context.Context, req GetChannelICalendarRequest) (*Response[GetChannelICalendarData], error)",
			RequestType: "GetChannelICalendarRequest",
			DataType:    "GetChannelICalendarData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-channel-icalendar",
	}),
	defineOperation("update-channel-stream-schedule", Operation{
		Name:           "Update Channel Stream Schedule",
		Method:         http.MethodPatch,
		Path:           "/helix/schedule/settings",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:schedule"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "is_vacation_enabled", Type: "Boolean"},
					{Name: "vacation_start_time", Type: "String"},
					{Name: "vacation_end_time", Type: "String"},
					{Name: "timezone", Type: "String"},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Schedule",
			ServiceType: "ScheduleService",
			Method:      "UpdateChannelStreamSchedule",
			Signature:   "func (s *ScheduleService) UpdateChannelStreamSchedule(ctx context.Context, req UpdateChannelStreamScheduleRequest) (*Response[UpdateChannelStreamScheduleData], error)",
			RequestType: "UpdateChannelStreamScheduleRequest",
			DataType:    "UpdateChannelStreamScheduleData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-channel-stream-schedule",
	}),
	defineOperation("create-channel-stream-schedule-segment", Operation{
		Name:           "Create Channel Stream Schedule Segment",
		Method:         http.MethodPost,
		Path:           "/helix/schedule/segment",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:schedule"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "start_time", Type: "String", Required: true},
					{Name: "timezone", Type: "String", Required: true},
					{Name: "duration", Type: "String", Required: true},
					{Name: "is_recurring", Type: "Boolean"},
					{Name: "category_id", Type: "String"},
					{Name: "title", Type: "String"},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Schedule",
			ServiceType: "ScheduleService",
			Method:      "CreateChannelStreamScheduleSegment",
			Signature:   "func (s *ScheduleService) CreateChannelStreamScheduleSegment(ctx context.Context, req CreateChannelStreamScheduleSegmentRequest) (*Response[CreateChannelStreamScheduleSegmentData], error)",
			RequestType: "CreateChannelStreamScheduleSegmentRequest",
			DataType:    "CreateChannelStreamScheduleSegmentData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#create-channel-stream-schedule-segment",
	}),
	defineOperation("update-channel-stream-schedule-segment", Operation{
		Name:           "Update Channel Stream Schedule Segment",
		Method:         http.MethodPatch,
		Path:           "/helix/schedule/segment",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:schedule"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "start_time", Type: "String"},
					{Name: "duration", Type: "String"},
					{Name: "category_id", Type: "String"},
					{Name: "title", Type: "String"},
					{Name: "is_canceled", Type: "Boolean"},
					{Name: "timezone", Type: "String"},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Schedule",
			ServiceType: "ScheduleService",
			Method:      "UpdateChannelStreamScheduleSegment",
			Signature:   "func (s *ScheduleService) UpdateChannelStreamScheduleSegment(ctx context.Context, req UpdateChannelStreamScheduleSegmentRequest) (*Response[UpdateChannelStreamScheduleSegmentData], error)",
			RequestType: "UpdateChannelStreamScheduleSegmentRequest",
			DataType:    "UpdateChannelStreamScheduleSegmentData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-channel-stream-schedule-segment",
	}),
	defineOperation("delete-channel-stream-schedule-segment", Operation{
		Name:           "Delete Channel Stream Schedule Segment",
		Method:         http.MethodDelete,
		Path:           "/helix/schedule/segment",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:schedule"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Schedule",
			ServiceType: "ScheduleService",
			Method:      "DeleteChannelStreamScheduleSegment",
			Signature:   "func (s *ScheduleService) DeleteChannelStreamScheduleSegment(ctx context.Context, req DeleteChannelStreamScheduleSegmentRequest) (*Response[DeleteChannelStreamScheduleSegmentData], error)",
			RequestType: "DeleteChannelStreamScheduleSegmentRequest",
			DataType:    "DeleteChannelStreamScheduleSegmentData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#delete-channel-stream-schedule-segment",
	}),
)
