package manifest

import "net/http"

var clipsOperations = operationsForGroup("Clips",
	defineOperation("create-clip", Operation{
		Name:           "Create Clip",
		Method:         http.MethodPost,
		Path:           "/helix/clips",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"clips:edit"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "title", Type: "String"},
					{Name: "duration", Type: "Float"},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{202, 400, 401, 403, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Clips",
			ServiceType: "ClipsService",
			Method:      "CreateClip",
			Signature:   "func (s *ClipsService) CreateClip(ctx context.Context, req CreateClipRequest) (*Response[CreateClipData], error)",
			RequestType: "CreateClipRequest",
			DataType:    "CreateClipData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#create-clip",
	}),
	defineOperation("create-clip-from-vod", Operation{
		Name:           "Create Clip From VOD",
		Method:         http.MethodPost,
		Path:           "/helix/videos/clips",
		Stability:      StabilityNew,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"editor:manage:clips", "channel:manage:clips"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "editor_id", Type: "String", Required: true},
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "vod_id", Type: "String", Required: true},
					{Name: "vod_offset", Type: "Integer", Required: true},
					{Name: "duration", Type: "Float"},
					{Name: "title", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{202, 400, 401, 403, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.Clips",
			ServiceType: "ExperimentalClipsService",
			Method:      "CreateClipFromVOD",
			Signature:   "func (s *ExperimentalClipsService) CreateClipFromVOD(ctx context.Context, req CreateClipFromVODRequest) (*Response[CreateClipFromVODData], error)",
			RequestType: "CreateClipFromVODRequest",
			DataType:    "CreateClipFromVODData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#create-clip-from-vod",
	}),
	defineOperation("get-clips", Operation{
		Name:           "Get Clips",
		Method:         http.MethodGet,
		Path:           "/helix/clips",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"unknown"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "game_id", Type: "String", Required: true},
					{Name: "id", Type: "String", Required: true},
					{Name: "started_at", Type: "String"},
					{Name: "ended_at", Type: "String"},
					{Name: "first", Type: "Integer"},
					{Name: "before", Type: "String"},
					{Name: "after", Type: "String"},
					{Name: "is_featured", Type: "Boolean"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 404}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Clips",
			ServiceType:    "ClipsService",
			Method:         "GetClips",
			Signature:      "func (s *ClipsService) GetClips(ctx context.Context, req GetClipsRequest) (*Response[GetClipsData], error)",
			PagerSignature: pagerSignature("func (s *ClipsService) GetClipsPager(req GetClipsRequest, opts ...PagerOption) (*Pager[GetClipsData], error)"),
			RequestType:    "GetClipsRequest",
			DataType:       "GetClipsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-clips",
	}),
	defineOperation("get-clips-download", Operation{
		Name:           "Get Clips Download",
		Method:         http.MethodGet,
		Path:           "/helix/clips/downloads",
		Stability:      StabilityNew,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"editor:manage:clips", "channel:manage:clips"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "editor_id", Type: "String", Required: true},
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "clip_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 500}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.Clips",
			ServiceType: "ExperimentalClipsService",
			Method:      "GetClipsDownload",
			Signature:   "func (s *ExperimentalClipsService) GetClipsDownload(ctx context.Context, req GetClipsDownloadRequest) (*Response[GetClipsDownloadData], error)",
			RequestType: "GetClipsDownloadRequest",
			DataType:    "GetClipsDownloadData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-clips-download",
	}),
)
