package manifest

import "net/http"

var moderationOperations = operationsForGroup("Moderation",
	defineOperation("check-automod-status", Operation{
		Name:           "Check AutoMod Status",
		Method:         http.MethodPost,
		Path:           "/helix/moderation/enforcements/status",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderation:read"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "data", Type: "Object[]", Required: true},
					{Name: "msg_id", Type: "String", Required: true},
					{Name: "msg_text", Type: "String", Required: true},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "CheckAutoModStatus",
			Signature:   "func (s *ModerationService) CheckAutoModStatus(ctx context.Context, req CheckAutoModStatusRequest) (*Response[CheckAutoModStatusData], error)",
			RequestType: "CheckAutoModStatusRequest",
			DataType:    "CheckAutoModStatusData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#check-automod-status",
	}),
	defineOperation("manage-held-automod-messages", Operation{
		Name:           "Manage Held AutoMod Messages",
		Method:         http.MethodPost,
		Path:           "/helix/moderation/automod/message",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:automod"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "user_id", Type: "String", Required: true},
					{Name: "msg_id", Type: "String", Required: true},
					{Name: "action", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 403, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "ManageHeldAutoModMessages",
			Signature:   "func (s *ModerationService) ManageHeldAutoModMessages(ctx context.Context, req ManageHeldAutoModMessagesRequest) (*Response[ManageHeldAutoModMessagesData], error)",
			RequestType: "ManageHeldAutoModMessagesRequest",
			DataType:    "ManageHeldAutoModMessagesData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#manage-held-automod-messages",
	}),
	defineOperation("get-automod-settings", Operation{
		Name:           "Get AutoMod Settings",
		Method:         http.MethodGet,
		Path:           "/helix/moderation/automod/settings",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:read:automod_settings", "moderator:manage:automod_settings"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "GetAutoModSettings",
			Signature:   "func (s *ModerationService) GetAutoModSettings(ctx context.Context, req GetAutoModSettingsRequest) (*Response[GetAutoModSettingsData], error)",
			RequestType: "GetAutoModSettingsRequest",
			DataType:    "GetAutoModSettingsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-automod-settings",
	}),
	defineOperation("update-automod-settings", Operation{
		Name:           "Update AutoMod Settings",
		Method:         http.MethodPut,
		Path:           "/helix/moderation/automod/settings",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:automod_settings"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "aggression", Type: "Integer"},
					{Name: "bullying", Type: "Integer"},
					{Name: "disability", Type: "Integer"},
					{Name: "misogyny", Type: "Integer"},
					{Name: "overall_level", Type: "Integer"},
					{Name: "race_ethnicity_or_religion", Type: "Integer"},
					{Name: "sex_based_terms", Type: "Integer"},
					{Name: "sexuality_sex_or_gender", Type: "Integer"},
					{Name: "swearing", Type: "Integer"},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "UpdateAutoModSettings",
			Signature:   "func (s *ModerationService) UpdateAutoModSettings(ctx context.Context, req UpdateAutoModSettingsRequest) (*Response[UpdateAutoModSettingsData], error)",
			RequestType: "UpdateAutoModSettingsRequest",
			DataType:    "UpdateAutoModSettingsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-automod-settings",
	}),
	defineOperation("get-banned-users", Operation{
		Name:           "Get Banned Users",
		Method:         http.MethodGet,
		Path:           "/helix/moderation/banned",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderation:read", "moderator:manage:banned_users"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "user_id", Type: "String"},
					{Name: "first", Type: "Integer"},
					{Name: "after", Type: "String"},
					{Name: "before", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Moderation",
			ServiceType:    "ModerationService",
			Method:         "GetBannedUsers",
			Signature:      "func (s *ModerationService) GetBannedUsers(ctx context.Context, req GetBannedUsersRequest) (*Response[GetBannedUsersData], error)",
			PagerSignature: pagerSignature("func (s *ModerationService) GetBannedUsersPager(req GetBannedUsersRequest, opts ...PagerOption) (*Pager[GetBannedUsersData], error)"),
			RequestType:    "GetBannedUsersRequest",
			DataType:       "GetBannedUsersData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-banned-users",
	}),
	defineOperation("ban-user", Operation{
		Name:           "Ban User",
		Method:         http.MethodPost,
		Path:           "/helix/moderation/bans",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:banned_users", "user:bot"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "data", Type: "Object", Required: true},
					{Name: "user_id", Type: "String", Required: true},
					{Name: "duration", Type: "Integer"},
					{Name: "reason", Type: "String"},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 409, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "BanUser",
			Signature:   "func (s *ModerationService) BanUser(ctx context.Context, req BanUserRequest) (*Response[BanUserData], error)",
			RequestType: "BanUserRequest",
			DataType:    "BanUserData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#ban-user",
	}),
	defineOperation("unban-user", Operation{
		Name:           "Unban User",
		Method:         http.MethodDelete,
		Path:           "/helix/moderation/bans",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:banned_users", "user:bot"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "user_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{204, 400, 401, 403, 409, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "UnbanUser",
			Signature:   "func (s *ModerationService) UnbanUser(ctx context.Context, req UnbanUserRequest) (*Response[UnbanUserData], error)",
			RequestType: "UnbanUserRequest",
			DataType:    "UnbanUserData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#unban-user",
	}),
	defineOperation("get-unban-requests", Operation{
		Name:           "Get Unban Requests",
		Method:         http.MethodGet,
		Path:           "/helix/moderation/unban_requests",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"moderator:read:unban_requests", "moderator:manage:unban_requests"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "status", Type: "String", Required: true},
					{Name: "user_id", Type: "String"},
					{Name: "after", Type: "String"},
					{Name: "first", Type: "Integer"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Moderation",
			ServiceType:    "ModerationService",
			Method:         "GetUnbanRequests",
			Signature:      "func (s *ModerationService) GetUnbanRequests(ctx context.Context, req GetUnbanRequestsRequest) (*Response[GetUnbanRequestsData], error)",
			PagerSignature: pagerSignature("func (s *ModerationService) GetUnbanRequestsPager(req GetUnbanRequestsRequest, opts ...PagerOption) (*Pager[GetUnbanRequestsData], error)"),
			RequestType:    "GetUnbanRequestsRequest",
			DataType:       "GetUnbanRequestsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-unban-requests",
	}),
	defineOperation("resolve-unban-requests", Operation{
		Name:           "Resolve Unban Requests",
		Method:         http.MethodPatch,
		Path:           "/helix/moderation/unban_requests",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"moderator:manage:unban_requests"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "unban_request_id", Type: "String", Required: true},
					{Name: "status", Type: "String", Required: true},
					{Name: "resolution_text", Type: "String"},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "ResolveUnbanRequests",
			Signature:   "func (s *ModerationService) ResolveUnbanRequests(ctx context.Context, req ResolveUnbanRequestsRequest) (*Response[ResolveUnbanRequestsData], error)",
			RequestType: "ResolveUnbanRequestsRequest",
			DataType:    "ResolveUnbanRequestsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#resolve-unban-requests",
	}),
	defineOperation("get-blocked-terms", Operation{
		Name:           "Get Blocked Terms",
		Method:         http.MethodGet,
		Path:           "/helix/moderation/blocked_terms",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:read:blocked_terms", "moderator:manage:blocked_terms"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "first", Type: "Integer"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Moderation",
			ServiceType:    "ModerationService",
			Method:         "GetBlockedTerms",
			Signature:      "func (s *ModerationService) GetBlockedTerms(ctx context.Context, req GetBlockedTermsRequest) (*Response[GetBlockedTermsData], error)",
			PagerSignature: pagerSignature("func (s *ModerationService) GetBlockedTermsPager(req GetBlockedTermsRequest, opts ...PagerOption) (*Pager[GetBlockedTermsData], error)"),
			RequestType:    "GetBlockedTermsRequest",
			DataType:       "GetBlockedTermsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-blocked-terms",
	}),
	defineOperation("add-blocked-term", Operation{
		Name:           "Add Blocked Term",
		Method:         http.MethodPost,
		Path:           "/helix/moderation/blocked_terms",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:blocked_terms"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "text", Type: "String", Required: true},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "AddBlockedTerm",
			Signature:   "func (s *ModerationService) AddBlockedTerm(ctx context.Context, req AddBlockedTermRequest) (*Response[AddBlockedTermData], error)",
			RequestType: "AddBlockedTermRequest",
			DataType:    "AddBlockedTermData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#add-blocked-term",
	}),
	defineOperation("remove-blocked-term", Operation{
		Name:           "Remove Blocked Term",
		Method:         http.MethodDelete,
		Path:           "/helix/moderation/blocked_terms",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:blocked_terms"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "RemoveBlockedTerm",
			Signature:   "func (s *ModerationService) RemoveBlockedTerm(ctx context.Context, req RemoveBlockedTermRequest) (*Response[RemoveBlockedTermData], error)",
			RequestType: "RemoveBlockedTermRequest",
			DataType:    "RemoveBlockedTermData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#remove-blocked-term",
	}),
	defineOperation("delete-chat-messages", Operation{
		Name:           "Delete Chat Messages",
		Method:         http.MethodDelete,
		Path:           "/helix/moderation/chat",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:chat_messages"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "message_id", Type: "String"},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 403, 404}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "DeleteChatMessages",
			Signature:   "func (s *ModerationService) DeleteChatMessages(ctx context.Context, req DeleteChatMessagesRequest) (*Response[DeleteChatMessagesData], error)",
			RequestType: "DeleteChatMessagesRequest",
			DataType:    "DeleteChatMessagesData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#delete-chat-messages",
	}),
	defineOperation("get-moderated-channels", Operation{
		Name:           "Get Moderated Channels",
		Method:         http.MethodGet,
		Path:           "/helix/moderation/channels",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"user:read:moderated_channels"},
		SubjectBinding: "user_id",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String", Required: true},
					{Name: "after", Type: "String"},
					{Name: "first", Type: "Integer"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", StatusUnknown: true},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Moderation",
			ServiceType:    "ModerationService",
			Method:         "GetModeratedChannels",
			Signature:      "func (s *ModerationService) GetModeratedChannels(ctx context.Context, req GetModeratedChannelsRequest) (*Response[GetModeratedChannelsData], error)",
			PagerSignature: pagerSignature("func (s *ModerationService) GetModeratedChannelsPager(req GetModeratedChannelsRequest, opts ...PagerOption) (*Pager[GetModeratedChannelsData], error)"),
			RequestType:    "GetModeratedChannelsRequest",
			DataType:       "GetModeratedChannelsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-moderated-channels",
	}),
	defineOperation("get-moderators", Operation{
		Name:           "Get Moderators",
		Method:         http.MethodGet,
		Path:           "/helix/moderation/moderators",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"moderation:read", "channel:manage:moderators"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "user_id", Type: "String"},
					{Name: "first", Type: "String"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Moderation",
			ServiceType:    "ModerationService",
			Method:         "GetModerators",
			Signature:      "func (s *ModerationService) GetModerators(ctx context.Context, req GetModeratorsRequest) (*Response[GetModeratorsData], error)",
			PagerSignature: pagerSignature("func (s *ModerationService) GetModeratorsPager(req GetModeratorsRequest, opts ...PagerOption) (*Pager[GetModeratorsData], error)"),
			RequestType:    "GetModeratorsRequest",
			DataType:       "GetModeratorsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-moderators",
	}),
	defineOperation("add-channel-moderator", Operation{
		Name:           "Add Channel Moderator",
		Method:         http.MethodPost,
		Path:           "/helix/moderation/moderators",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:moderators"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "user_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 422, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "AddChannelModerator",
			Signature:   "func (s *ModerationService) AddChannelModerator(ctx context.Context, req AddChannelModeratorRequest) (*Response[AddChannelModeratorData], error)",
			RequestType: "AddChannelModeratorRequest",
			DataType:    "AddChannelModeratorData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#add-channel-moderator",
	}),
	defineOperation("remove-channel-moderator", Operation{
		Name:           "Remove Channel Moderator",
		Method:         http.MethodDelete,
		Path:           "/helix/moderation/moderators",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:moderators"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "user_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "RemoveChannelModerator",
			Signature:   "func (s *ModerationService) RemoveChannelModerator(ctx context.Context, req RemoveChannelModeratorRequest) (*Response[RemoveChannelModeratorData], error)",
			RequestType: "RemoveChannelModeratorRequest",
			DataType:    "RemoveChannelModeratorData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#remove-channel-moderator",
	}),
	defineOperation("get-vips", Operation{
		Name:           "Get VIPs",
		Method:         http.MethodGet,
		Path:           "/helix/channels/vips",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:read:vips", "channel:manage:vips"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String"},
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "first", Type: "Integer"},
					{Name: "after", Type: "String"},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401}},
		Pagination: PaginationSpec{Shape: "cursor", CursorParameter: "after"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:       "Client.Moderation",
			ServiceType:    "ModerationService",
			Method:         "GetVIPs",
			Signature:      "func (s *ModerationService) GetVIPs(ctx context.Context, req GetVIPsRequest) (*Response[GetVIPsData], error)",
			PagerSignature: pagerSignature("func (s *ModerationService) GetVIPsPager(req GetVIPsRequest, opts ...PagerOption) (*Pager[GetVIPsData], error)"),
			RequestType:    "GetVIPsRequest",
			DataType:       "GetVIPsData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-vips",
	}),
	defineOperation("add-channel-vip", Operation{
		Name:           "Add Channel VIP",
		Method:         http.MethodPost,
		Path:           "/helix/channels/vips",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:vips"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String", Required: true},
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 404, 409, 422, 425, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "AddChannelVIP",
			Signature:   "func (s *ModerationService) AddChannelVIP(ctx context.Context, req AddChannelVIPRequest) (*Response[AddChannelVIPData], error)",
			RequestType: "AddChannelVIPRequest",
			DataType:    "AddChannelVIPData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#add-channel-vip",
	}),
	defineOperation("remove-channel-vip", Operation{
		Name:           "Remove Channel VIP",
		Method:         http.MethodDelete,
		Path:           "/helix/channels/vips",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassUser},
		Scopes:         []string{"channel:manage:vips"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "user_id", Type: "String", Required: true},
					{Name: "broadcaster_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "unknown", Status: []int{204, 400, 401, 403, 404, 422, 429}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "RemoveChannelVIP",
			Signature:   "func (s *ModerationService) RemoveChannelVIP(ctx context.Context, req RemoveChannelVIPRequest) (*Response[RemoveChannelVIPData], error)",
			RequestType: "RemoveChannelVIPRequest",
			DataType:    "RemoveChannelVIPData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#remove-channel-vip",
	}),
	defineOperation("update-shield-mode-status", Operation{
		Name:           "Update Shield Mode Status",
		Method:         http.MethodPut,
		Path:           "/helix/moderation/shield_mode",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:shield_mode"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "is_active", Type: "Boolean", Required: true},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "UpdateShieldModeStatus",
			Signature:   "func (s *ModerationService) UpdateShieldModeStatus(ctx context.Context, req UpdateShieldModeStatusRequest) (*Response[UpdateShieldModeStatusData], error)",
			RequestType: "UpdateShieldModeStatusRequest",
			DataType:    "UpdateShieldModeStatusData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#update-shield-mode-status",
	}),
	defineOperation("get-shield-mode-status", Operation{
		Name:           "Get Shield Mode Status",
		Method:         http.MethodGet,
		Path:           "/helix/moderation/shield_mode",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:read:shield_mode", "moderator:manage:shield_mode"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
			BodyReconstructible: true,
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "GetShieldModeStatus",
			Signature:   "func (s *ModerationService) GetShieldModeStatus(ctx context.Context, req GetShieldModeStatusRequest) (*Response[GetShieldModeStatusData], error)",
			RequestType: "GetShieldModeStatusRequest",
			DataType:    "GetShieldModeStatusData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#get-shield-mode-status",
	}),
	defineOperation("warn-chat-user", Operation{
		Name:           "Warn Chat User",
		Method:         http.MethodPost,
		Path:           "/helix/moderation/warnings",
		Stability:      StabilityStable,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:warnings"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body": {
					{Name: "data", Type: "Object", Required: true},
					{Name: "user_id", Type: "String", Required: true},
					{Name: "reason", Type: "String", Required: true},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403, 409, 429, 500}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Implementation: ImplementationSpec{
			Selector:    "Client.Moderation",
			ServiceType: "ModerationService",
			Method:      "WarnChatUser",
			Signature:   "func (s *ModerationService) WarnChatUser(ctx context.Context, req WarnChatUserRequest) (*Response[WarnChatUserData], error)",
			RequestType: "WarnChatUserRequest",
			DataType:    "WarnChatUserData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#warn-chat-user",
	}),
	defineOperation("add-suspicious-status-to-chat-user", Operation{
		Name:           "Add Suspicious Status to Chat User",
		Method:         http.MethodPost,
		Path:           "/helix/moderation/suspicious_users",
		Stability:      StabilityNew,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:suspicious_users"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"body_parameters": {
					{Name: "user_id", Type: "String", Required: true},
					{Name: "status", Type: "String", Required: true},
				},
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.Moderation",
			ServiceType: "ExperimentalModerationService",
			Method:      "AddSuspiciousStatusToChatUser",
			Signature:   "func (s *ExperimentalModerationService) AddSuspiciousStatusToChatUser(ctx context.Context, req AddSuspiciousStatusToChatUserRequest) (*Response[AddSuspiciousStatusToChatUserData], error)",
			RequestType: "AddSuspiciousStatusToChatUserRequest",
			DataType:    "AddSuspiciousStatusToChatUserData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#add-suspicious-status-to-chat-user",
	}),
	defineOperation("remove-suspicious-status-from-chat-user", Operation{
		Name:           "Remove Suspicious Status From Chat User",
		Method:         http.MethodDelete,
		Path:           "/helix/moderation/suspicious_users",
		Stability:      StabilityNew,
		TokenClasses:   []TokenClass{TokenClassApp, TokenClassUser},
		Scopes:         []string{"moderator:manage:suspicious_users"},
		SubjectBinding: "unknown",
		Request: RequestSpec{
			Locations: map[string][]RequestField{
				"query_parameters": {
					{Name: "broadcaster_id", Type: "String", Required: true},
					{Name: "moderator_id", Type: "String", Required: true},
					{Name: "user_id", Type: "String", Required: true},
				},
			},
		},
		Response:   ResponseSpec{Format: "json", Status: []int{200, 400, 401, 403}},
		Pagination: PaginationSpec{Shape: "none", CursorParameter: "unknown"},
		Replay:     ReplaySpec{BucketWaitable: true},
		Implementation: ImplementationSpec{
			Selector:    "Client.Experimental.Moderation",
			ServiceType: "ExperimentalModerationService",
			Method:      "RemoveSuspiciousStatusFromChatUser",
			Signature:   "func (s *ExperimentalModerationService) RemoveSuspiciousStatusFromChatUser(ctx context.Context, req RemoveSuspiciousStatusFromChatUserRequest) (*Response[RemoveSuspiciousStatusFromChatUserData], error)",
			RequestType: "RemoveSuspiciousStatusFromChatUserRequest",
			DataType:    "RemoveSuspiciousStatusFromChatUserData",
		},
		Source: "https://dev.twitch.tv/docs/api/reference/#remove-suspicious-status-from-chat-user",
	}),
)
